export type BlogCategory = {
  id: number;
  name: string;
  slug: string;
};
export type BlogPost = {
  id: number;
  title: string;
  slug: string;
  categorySlug: string;
  excerpt: string;
  content: string;
  coverImage: string;
  status: "published" | "draft";
  isFeatured: boolean;
  publishedAt: string;
};
export const blogCategories: BlogCategory[] = [
  { id: 1, name: 'Postpartum Recovery', slug: 'postpartum-recovery' },
  { id: 2, name: 'Postpartum Meal Knowledge', slug: 'postpartum-meal' },
  { id: 3, name: 'Breastfeeding Nutrition', slug: 'breastfeeding-nutrition' },
  { id: 4, name: 'GTA Local Guide', slug: 'gta-local-guide' },
  { id: 5, name: 'Baby Care', slug: 'baby-care' },
  { id: 6, name: 'Pregnancy Nutrition', slug: 'pregnancy-nutrition' },
  { id: 7, name: 'Customer Stories', slug: 'customer-stories' },
  { id: 8, name: 'Jiahua News', slug: 'jiahua-news' },
];

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: 'What to Eat During Postpartum Recovery in Canada: A Guide for GTA Chinese Families',
    slug: 'postpartum-meals-in-canada',
    categorySlug: 'postpartum-meal',
    excerpt: 'Living in Canada means balancing traditional postpartum practices with local family routines. This guide explains key meal focuses across different recovery stages.',
    content: "### What to Eat During Postpartum Recovery in Canada: A Guide for GTA Chinese Families\n\nLiving in Canada means balancing traditional postpartum practices with local family routines. This guide explains key meal focuses across different recovery stages.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nLiving in Canada means balancing traditional postpartum practices with local family routines. This guide explains key meal focuses across different recovery stages.\n",
    coverImage: '/images/blog/postpartum-meals-in-canada.png',
    status: "published",
    isFeatured: true,
    publishedAt: '2026-08-01',
  },
  {
    id: 2,
    title: 'C-Section Recovery Diet Guide: How to Eat More Comfortably After Delivery',
    slug: 'c-section-recovery-diet',
    categorySlug: 'postpartum-recovery',
    excerpt: 'C-section recovery meals should be gentle, light, and easy to digest. This guide helps families understand meal priorities after surgery.',
    content: "### C-Section Recovery Diet Guide: How to Eat More Comfortably After Delivery\n\nC-section recovery meals should be gentle, light, and easy to digest. This guide helps families understand meal priorities after surgery.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nC-section recovery meals should be gentle, light, and easy to digest. This guide helps families understand meal priorities after surgery.\n",
    coverImage: '/images/blog/c-section-recovery-diet.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-03',
  },
  {
    id: 3,
    title: 'How Should Breastfeeding Mothers Support Their Nutrition?',
    slug: 'breastfeeding-nutrition-guide',
    categorySlug: 'breastfeeding-nutrition',
    excerpt: 'Breastfeeding nutrition affects both recovery and daily caregiving rhythm. This article shares common meal planning principles and reminders.',
    content: "### How Should Breastfeeding Mothers Support Their Nutrition?\n\nBreastfeeding nutrition affects both recovery and daily caregiving rhythm. This article shares common meal planning principles and reminders.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nBreastfeeding nutrition affects both recovery and daily caregiving rhythm. This article shares common meal planning principles and reminders.\n",
    coverImage: '/images/blog/breastfeeding-nutrition-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-05',
  },
  {
    id: 4,
    title: 'How to Choose a Postpartum Meal Service in the GTA',
    slug: 'gta-postpartum-meal-service-guide',
    categorySlug: 'gta-local-guide',
    excerpt: 'When choosing postpartum meals in Markham, Richmond Hill, North York, Aurora, and nearby areas, focus on menu structure, delivery coverage, communication, and service stability.',
    content: "### How to Choose a Postpartum Meal Service in the GTA\n\nWhen choosing postpartum meals in Markham, Richmond Hill, North York, Aurora, and nearby areas, focus on menu structure, delivery coverage, communication, and service stability.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nWhen choosing postpartum meals in Markham, Richmond Hill, North York, Aurora, and nearby areas, focus on menu structure, delivery coverage, communication, and service stability.\n",
    coverImage: '/images/blog/gta-postpartum-meal-service-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-07',
  },
  {
    id: 5,
    title: '30-Day Natural Birth Recovery Diet Guide',
    slug: 'natural-birth-30-day-diet-guide',
    categorySlug: 'postpartum-recovery',
    excerpt: 'Recovery after vaginal delivery is usually gradual. This guide breaks down meal focuses from week one to week four.',
    content: "### 30-Day Natural Birth Recovery Diet Guide\n\nRecovery after vaginal delivery is usually gradual. This guide breaks down meal focuses from week one to week four.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nRecovery after vaginal delivery is usually gradual. This guide breaks down meal focuses from week one to week four.\n",
    coverImage: '/images/blog/natural-birth-30-day-diet-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-10',
  },
  {
    id: 6,
    title: 'How Early Should You Book Postpartum Meals?',
    slug: 'when-to-book-postpartum-meals',
    categorySlug: 'postpartum-meal',
    excerpt: 'Many families start looking into postpartum meals close to the due date. Planning earlier helps confirm delivery areas, menu preferences, and special needs.',
    content: "### How Early Should You Book Postpartum Meals?\n\nMany families start looking into postpartum meals close to the due date. Planning earlier helps confirm delivery areas, menu preferences, and special needs.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nMany families start looking into postpartum meals close to the due date. Planning earlier helps confirm delivery areas, menu preferences, and special needs.\n",
    coverImage: '/images/blog/when-to-book-postpartum-meals.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-12',
  },
  {
    id: 7,
    title: 'How to Choose Postpartum Meal Delivery in Markham',
    slug: 'markham-postpartum-meal-delivery-guide',
    categorySlug: 'gta-local-guide',
    excerpt: 'Markham has many Chinese families and strong demand for postpartum meals. This guide explains what to consider when choosing a local service.',
    content: "### How to Choose Postpartum Meal Delivery in Markham\n\nMarkham has many Chinese families and strong demand for postpartum meals. This guide explains what to consider when choosing a local service.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nMarkham has many Chinese families and strong demand for postpartum meals. This guide explains what to consider when choosing a local service.\n",
    coverImage: '/images/blog/markham-postpartum-meal-delivery-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-15',
  },
  {
    id: 8,
    title: 'What to Eat During Week 2 of Postpartum Recovery',
    slug: 'postpartum-meal-week-2-guide',
    categorySlug: 'postpartum-meal',
    excerpt: 'During the second postpartum week, meals can gradually increase nutrient density while staying gentle and easy to enjoy.',
    content: "### What to Eat During Week 2 of Postpartum Recovery\n\nDuring the second postpartum week, meals can gradually increase nutrient density while staying gentle and easy to enjoy.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nDuring the second postpartum week, meals can gradually increase nutrient density while staying gentle and easy to enjoy.\n",
    coverImage: '/images/blog/postpartum-meal-week-2.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-18',
  },
  {
    id: 9,
    title: 'What to Eat During Week 3 of Postpartum Recovery',
    slug: 'postpartum-meal-week-3-guide',
    categorySlug: 'postpartum-meal',
    excerpt: 'By the third week, many mothers enter a more stable recovery stage and can gradually add variety and balanced nourishment.',
    content: "### What to Eat During Week 3 of Postpartum Recovery\n\nBy the third week, many mothers enter a more stable recovery stage and can gradually add variety and balanced nourishment.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nBy the third week, many mothers enter a more stable recovery stage and can gradually add variety and balanced nourishment.\n",
    coverImage: '/images/blog/postpartum-meal-week-3.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-08-20',
  },
  {
    id: 10,
    title: 'What to Eat During Week 4 of Postpartum Recovery',
    slug: 'postpartum-meal-week-4-guide',
    categorySlug: 'postpartum-meal',
    excerpt: 'During the fourth week, meals can move closer to everyday eating while staying gentle, balanced, and regular.',
    content: "### What to Eat During Week 4 of Postpartum Recovery\n\nDuring the fourth week, meals can move closer to everyday eating while staying gentle, balanced, and regular.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nDuring the fourth week, meals can move closer to everyday eating while staying gentle, balanced, and regular.\n",
    coverImage: '/images/blog/postpartum-meal-week-4.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-01',
  },
  {
    id: 11,
    title: 'How to Arrange Soups During the First Postpartum Week',
    slug: 'postpartum-week-1-soup-guide',
    categorySlug: 'postpartum-meal',
    excerpt: 'Soups in the first postpartum week should not be too oily. Gentle, light, and easy-to-drink soups are usually more suitable.',
    content: "### How to Arrange Soups During the First Postpartum Week\n\nSoups in the first postpartum week should not be too oily. Gentle, light, and easy-to-drink soups are usually more suitable.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nSoups in the first postpartum week should not be too oily. Gentle, light, and easy-to-drink soups are usually more suitable.\n",
    coverImage: '/images/blog/postpartum-week-1-soup-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-02',
  },
  {
    id: 12,
    title: 'Can Mothers Eat Vegetables During Postpartum Recovery?',
    slug: 'postpartum-vegetables-guide',
    categorySlug: 'postpartum-meal',
    excerpt: 'Postpartum meals should not rely only on meat and soup. Cooked vegetables are an important part of a balanced recovery meal plan.',
    content: "### Can Mothers Eat Vegetables During Postpartum Recovery?\n\nPostpartum meals should not rely only on meat and soup. Cooked vegetables are an important part of a balanced recovery meal plan.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nPostpartum meals should not rely only on meat and soup. Cooked vegetables are an important part of a balanced recovery meal plan.\n",
    coverImage: '/images/blog/postpartum-vegetables-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-03',
  },
  {
    id: 13,
    title: 'How Can Postpartum Meals Be Nutritious Without Being Oily?',
    slug: 'postpartum-meal-less-oily-guide',
    categorySlug: 'postpartum-meal',
    excerpt: 'Postpartum meals do not have to be greasy. Lighter cooking methods can still support nutrition and recovery.',
    content: "### How Can Postpartum Meals Be Nutritious Without Being Oily?\n\nPostpartum meals do not have to be greasy. Lighter cooking methods can still support nutrition and recovery.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nPostpartum meals do not have to be greasy. Lighter cooking methods can still support nutrition and recovery.\n",
    coverImage: '/images/blog/postpartum-meal-less-oily-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-04',
  },
  {
    id: 14,
    title: 'Postpartum Constipation: What Can Diet Help With?',
    slug: 'postpartum-constipation-diet-tips',
    categorySlug: 'postpartum-recovery',
    excerpt: 'Postpartum constipation is common. Hydration, cooked vegetables, staple foods, and regular meals can help support a better routine.',
    content: "### Postpartum Constipation: What Can Diet Help With?\n\nPostpartum constipation is common. Hydration, cooked vegetables, staple foods, and regular meals can help support a better routine.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nPostpartum constipation is common. Hydration, cooked vegetables, staple foods, and regular meals can help support a better routine.\n",
    coverImage: '/images/blog/postpartum-constipation-diet-tips.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-05',
  },
  {
    id: 15,
    title: 'How to Arrange Meals When Appetite Is Low After Delivery',
    slug: 'postpartum-low-appetite-meal-guide',
    categorySlug: 'postpartum-recovery',
    excerpt: 'When appetite is low after delivery, it is better to start with small, gentle meals instead of forcing heavy nourishment.',
    content: "### How to Arrange Meals When Appetite Is Low After Delivery\n\nWhen appetite is low after delivery, it is better to start with small, gentle meals instead of forcing heavy nourishment.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nWhen appetite is low after delivery, it is better to start with small, gentle meals instead of forcing heavy nourishment.\n",
    coverImage: '/images/blog/postpartum-low-appetite-meal-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-06',
  },
  {
    id: 16,
    title: 'What to Eat During Week 2 After a C-Section',
    slug: 'c-section-week-2-diet-guide',
    categorySlug: 'postpartum-recovery',
    excerpt: 'During the second week after a C-section, nutrition can gradually increase, but meals should remain light and easy to digest.',
    content: "### What to Eat During Week 2 After a C-Section\n\nDuring the second week after a C-section, nutrition can gradually increase, but meals should remain light and easy to digest.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nDuring the second week after a C-section, nutrition can gradually increase, but meals should remain light and easy to digest.\n",
    coverImage: '/images/blog/c-section-week-2-diet-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-07',
  },
  {
    id: 17,
    title: 'Convenient Night Snacks for Breastfeeding Mothers',
    slug: 'breastfeeding-night-snack-guide',
    categorySlug: 'breastfeeding-nutrition',
    excerpt: 'Night feeding can take energy. Preparing simple, gentle snacks can make nighttime care easier for mothers.',
    content: "### Convenient Night Snacks for Breastfeeding Mothers\n\nNight feeding can take energy. Preparing simple, gentle snacks can make nighttime care easier for mothers.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nNight feeding can take energy. Preparing simple, gentle snacks can make nighttime care easier for mothers.\n",
    coverImage: '/images/blog/breastfeeding-night-snack-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-08',
  },
  {
    id: 18,
    title: 'Can Breastfeeding Mothers Drink Soup?',
    slug: 'breastfeeding-soup-guide',
    categorySlug: 'breastfeeding-nutrition',
    excerpt: 'Soups can be part of breastfeeding nutrition, but the focus should be light, regular, and comfortable for the mother.',
    content: "### Can Breastfeeding Mothers Drink Soup?\n\nSoups can be part of breastfeeding nutrition, but the focus should be light, regular, and comfortable for the mother.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nSoups can be part of breastfeeding nutrition, but the focus should be light, regular, and comfortable for the mother.\n",
    coverImage: '/images/blog/breastfeeding-soup-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-09',
  },
  {
    id: 19,
    title: 'When Should Families Start Preparing Postpartum Meals in the Third Trimester?',
    slug: 'third-trimester-postpartum-meal-prep',
    categorySlug: 'pregnancy-nutrition',
    excerpt: 'During the third trimester, families can begin learning about postpartum meal plans and delivery options.',
    content: "### When Should Families Start Preparing Postpartum Meals in the Third Trimester?\n\nDuring the third trimester, families can begin learning about postpartum meal plans and delivery options.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nDuring the third trimester, families can begin learning about postpartum meal plans and delivery options.\n",
    coverImage: '/images/blog/third-trimester-postpartum-meal-prep.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-10',
  },
  {
    id: 20,
    title: 'Postpartum Meal Booking Checklist Before the Due Date',
    slug: 'postpartum-meal-booking-checklist',
    categorySlug: 'pregnancy-nutrition',
    excerpt: 'Preparing key information before booking postpartum meals can make consultation clearer and faster.',
    content: "### Postpartum Meal Booking Checklist Before the Due Date\n\nPreparing key information before booking postpartum meals can make consultation clearer and faster.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nPreparing key information before booking postpartum meals can make consultation clearer and faster.\n",
    coverImage: '/images/blog/postpartum-meal-booking-checklist.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-11',
  },
  {
    id: 21,
    title: 'What Should Families Prepare During the Baby’s First Week Home?',
    slug: 'newborn-first-week-home-guide',
    categorySlug: 'baby-care',
    excerpt: 'During the first week home with a newborn, families need stable routines and fewer last-minute pressures.',
    content: "### What Should Families Prepare During the Baby’s First Week Home?\n\nDuring the first week home with a newborn, families need stable routines and fewer last-minute pressures.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nDuring the first week home with a newborn, families need stable routines and fewer last-minute pressures.\n",
    coverImage: '/images/blog/newborn-first-week-home-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-12',
  },
  {
    id: 22,
    title: 'How to Arrange Family Care Before the Baby’s First Month',
    slug: 'baby-first-month-family-routine',
    categorySlug: 'baby-care',
    excerpt: 'Before the baby’s first month, the key is building a simple and practical daily care rhythm.',
    content: "### How to Arrange Family Care Before the Baby’s First Month\n\nBefore the baby’s first month, the key is building a simple and practical daily care rhythm.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nBefore the baby’s first month, the key is building a simple and practical daily care rhythm.\n",
    coverImage: '/images/blog/baby-first-month-family-routine.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-13',
  },
  {
    id: 23,
    title: 'How to Choose Postpartum Meal Delivery in Richmond Hill',
    slug: 'richmond-hill-postpartum-meal-guide',
    categorySlug: 'gta-local-guide',
    excerpt: 'Families in Richmond Hill can focus on delivery coverage, stage-based menus, and communication efficiency when choosing a service.',
    content: "### How to Choose Postpartum Meal Delivery in Richmond Hill\n\nFamilies in Richmond Hill can focus on delivery coverage, stage-based menus, and communication efficiency when choosing a service.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nFamilies in Richmond Hill can focus on delivery coverage, stage-based menus, and communication efficiency when choosing a service.\n",
    coverImage: '/images/blog/richmond-hill-postpartum-meal-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-14',
  },
  {
    id: 24,
    title: 'How to Choose Postpartum Meal Delivery in North York',
    slug: 'north-york-postpartum-meal-guide',
    categorySlug: 'gta-local-guide',
    excerpt: 'North York is a large area, so confirming delivery coverage and meal arrangements in advance is important.',
    content: "### How to Choose Postpartum Meal Delivery in North York\n\nNorth York is a large area, so confirming delivery coverage and meal arrangements in advance is important.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nNorth York is a large area, so confirming delivery coverage and meal arrangements in advance is important.\n",
    coverImage: '/images/blog/north-york-postpartum-meal-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-15',
  },
  {
    id: 25,
    title: 'Which Families Benefit From Postpartum Meal Delivery in Aurora?',
    slug: 'aurora-postpartum-meal-guide',
    categorySlug: 'gta-local-guide',
    excerpt: 'For Aurora families without long-term help from relatives, postpartum meal delivery can reduce daily cooking pressure.',
    content: "### Which Families Benefit From Postpartum Meal Delivery in Aurora?\n\nFor Aurora families without long-term help from relatives, postpartum meal delivery can reduce daily cooking pressure.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nFor Aurora families without long-term help from relatives, postpartum meal delivery can reduce daily cooking pressure.\n",
    coverImage: '/images/blog/aurora-postpartum-meal-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-16',
  },
  {
    id: 26,
    title: 'How Jiahua Arranges Stage-Based Postpartum Menus',
    slug: 'jiahua-staged-menu-guide',
    categorySlug: 'jiahua-news',
    excerpt: 'Jiahua designs meals by postpartum recovery stage to help mothers recover gradually and comfortably.',
    content: "### How Jiahua Arranges Stage-Based Postpartum Menus\n\nJiahua designs meals by postpartum recovery stage to help mothers recover gradually and comfortably.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nJiahua designs meals by postpartum recovery stage to help mothers recover gradually and comfortably.\n",
    coverImage: '/images/blog/jiahua-staged-menu-guide.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-17',
  },
  {
    id: 27,
    title: 'Customer Story: Preparing Postpartum Meals Early Made Recovery Calmer',
    slug: 'customer-story-prepared-postpartum-meals',
    categorySlug: 'customer-stories',
    excerpt: 'One family reduced many last-minute pressures during the first postpartum week by arranging meals in advance.',
    content: "### Customer Story: Preparing Postpartum Meals Early Made Recovery Calmer\n\nOne family reduced many last-minute pressures during the first postpartum week by arranging meals in advance.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nOne family reduced many last-minute pressures during the first postpartum week by arranging meals in advance.\n",
    coverImage: '/images/blog/customer-story-prepared-postpartum-meals.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-18',
  },
  {
    id: 28,
    title: 'Customer Story: First-Time Postpartum Recovery Does Not Need a Complicated Menu',
    slug: 'customer-story-simple-postpartum-meals',
    categorySlug: 'customer-stories',
    excerpt: 'First-time families often worry about many details, but stable, gentle, and sustainable meals are often most helpful.',
    content: "### Customer Story: First-Time Postpartum Recovery Does Not Need a Complicated Menu\n\nFirst-time families often worry about many details, but stable, gentle, and sustainable meals are often most helpful.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nFirst-time families often worry about many details, but stable, gentle, and sustainable meals are often most helpful.\n",
    coverImage: '/images/blog/customer-story-simple-postpartum-meals.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-19',
  },
  {
    id: 29,
    title: 'Postpartum Meals vs. Regular Takeout: What Is the Difference?',
    slug: 'postpartum-meal-vs-takeout',
    categorySlug: 'postpartum-meal',
    excerpt: 'The difference between postpartum meals and regular takeout lies in stage-based planning, gentle flavors, and recovery-focused needs.',
    content: "### Postpartum Meals vs. Regular Takeout: What Is the Difference?\n\nThe difference between postpartum meals and regular takeout lies in stage-based planning, gentle flavors, and recovery-focused needs.\n\n#### Key Points\n- Choose meals that match the mother's recovery stage.\n- Keep meals gentle, balanced, and practical for daily family routines.\n- Adjust based on delivery method, breastfeeding needs, appetite, and dietary restrictions.\n\n#### Family Planning Tips\n\nEvery family has different postpartum care conditions. A practical meal plan should consider the mother's appetite, recovery status, caregiving support, and delivery arrangements.\n\n#### Jiahua's Suggestion\n\nJiahua Postpartum Meals recommends confirming delivery area, meal preferences, dietary restrictions, and due date arrangements in advance. Postpartum meals should be gentle, regular, stage-based, and adjusted according to real feedback from the mother.\n\n#### Summary\n\nThe difference between postpartum meals and regular takeout lies in stage-based planning, gentle flavors, and recovery-focused needs.\n",
    coverImage: '/images/blog/postpartum-meal-vs-takeout.png',
    status: "published",
    isFeatured: false,
    publishedAt: '2026-09-20',
  },
];

export function getCategoryBySlug(slug: string) {
  return blogCategories.find((category) => category.slug === slug) ?? null;
}

export function getPostBySlug(slug: string) {
  return blogPosts.find((post) => post.slug === slug && post.status === "published") ?? null;
}

export function getPublishedPosts() {
  return [...blogPosts]
    .filter((post) => post.status === "published")
    .sort((a, b) => {
      if (a.isFeatured !== b.isFeatured) return a.isFeatured ? -1 : 1;
      return new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime();
    });
}
